msgid ""
msgstr ""
"Project-Id-Version: kolibri\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-11-01 22:12-0700\n"
"PO-Revision-Date: 2021-11-02 05:29\n"
"Last-Translator: \n"
"Language-Team: Italian\n"
"Language: it_IT\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: kolibri\n"
"X-Crowdin-Project-ID: 201933\n"
"X-Crowdin-Language: it\n"
"X-Crowdin-File: /release-v0.15.x/django.po\n"
"X-Crowdin-File-ID: 4105\n"

#: core/auth/constants/commands_errors.py:17
msgid "Unexpected exception [{}]: {}"
msgstr "Eccezione imprevista [{}]: {}"

#: core/auth/constants/commands_errors.py:20
msgctxt "Error report message when the allowed number of digits has been exceeded."
msgid "Content of cell '{}' is too long"
msgstr "Il contenuto della cella '{}' è troppo lungo"

#: core/auth/constants/commands_errors.py:24
msgctxt "Error report message when the cell contains an improper data format."
msgid "Content of cell '{}' is not valid"
msgstr "Il contenuto della cella '{}' non è valido"

#: core/auth/constants/commands_errors.py:26
msgid "Duplicated username"
msgstr "Nome utente duplicato"

#: core/auth/constants/commands_errors.py:28
#: core/auth/management/commands/bulkimportusers.py:85
msgid "Username only can contain characters, numbers and underscores"
msgstr "Il nome utente può contenere solo caratteri, numeri e trattini bassi"

#: core/auth/constants/commands_errors.py:30
msgid "The column '{}' is required"
msgstr "La colonna \"{}\" è obbligatoria"

#: core/auth/constants/commands_errors.py:31
msgid "Mix of valid and/or invalid header labels found in first row"
msgstr "Mix di etichette di intestazione valide e/o non valide trovate nella prima riga"

#: core/auth/constants/commands_errors.py:33
msgid "No default facility exists. Make sure to set up a facility on the device before running this command"
msgstr "Non esiste nessuna struttura predefinita. Assicurati di impostare una struttura sul dispositivo prima di eseguire questo comando"

#: core/auth/constants/commands_errors.py:35
#: core/auth/management/commands/bulkimportusers.py:99
msgid "Error trying to read csv file: {}"
msgstr "Errore durante il tentativo di leggere il file CSV: {}"

#: core/auth/constants/commands_errors.py:36
#: core/auth/management/commands/bulkimportusers.py:100
msgid "Error trying to write csv file: {}"
msgstr "Errore durante il tentativo di scrivere il file CSV: {}"

#: core/auth/management/commands/bulkexportusers.py:42
#: core/auth/management/commands/bulkexportusers.py:124
msgid "Database ID ({})"
msgstr "ID Database ({})"

#: core/auth/management/commands/bulkexportusers.py:43
#: core/auth/management/commands/bulkexportusers.py:125
msgid "Username ({})"
msgstr "Nome Utente ({})"

#: core/auth/management/commands/bulkexportusers.py:44
#: core/auth/management/commands/bulkexportusers.py:126
msgid "Password ({})"
msgstr "Password ({})"

#: core/auth/management/commands/bulkexportusers.py:45
#: core/auth/management/commands/bulkexportusers.py:127
msgid "Full name ({})"
msgstr "Nome completo ({})"

#: core/auth/management/commands/bulkexportusers.py:50
msgctxt "CSV column header for the type of user: ADMIN, LEARNER, COACH..."
msgid "User type ({})"
msgstr "Tipologia utente ({})"

#: core/auth/management/commands/bulkexportusers.py:53
#: core/auth/management/commands/bulkexportusers.py:135
msgid "Identifier ({})"
msgstr "Identificatore ({})"

#: core/auth/management/commands/bulkexportusers.py:54
#: core/auth/management/commands/bulkexportusers.py:136
msgid "Birth year ({})"
msgstr "Anno di nascita ({})"

#: core/auth/management/commands/bulkexportusers.py:55
#: core/auth/management/commands/bulkexportusers.py:137
msgid "Gender ({})"
msgstr "Genere ({})"

#: core/auth/management/commands/bulkexportusers.py:60
msgctxt "CSV column header for the list of classrooms names where the learner is going to be enrolled"
msgid "Learner enrollment ({})"
msgstr "Iscrizione dello studente ({})"

#: core/auth/management/commands/bulkexportusers.py:67
msgctxt "CSV column header for the list of classrooms names where the tutor is going to be a coach"
msgid "Coach assignment ({})"
msgstr "Assegnazione Insegnante ({})"

#: core/auth/management/commands/bulkexportusers.py:132
msgctxt "CSV header for the type of user: ADMIN, LEARNER, COACH..."
msgid "User type ({})"
msgstr "Tipologia utente ({})"

#: core/auth/management/commands/bulkexportusers.py:142
msgctxt "CSV file header for the list of classrooms names where the learner is going to be enrolled"
msgid "Learner enrollment ({})"
msgstr "Iscrizione dello studente ({})"

#: core/auth/management/commands/bulkexportusers.py:149
msgctxt "CSV file header for the list of classrooms names where the tutor is going to be a coach"
msgid "Coach assignment ({})"
msgstr "Assegnazione Insegnante ({})"

#: core/auth/management/commands/bulkimportusers.py:76
msgctxt "Error message that might appear when there's a programming error importing a CSV file"
msgid "Unexpected error [{}]: {}"
msgstr "Errore imprevisto [{}]: {}"

#: core/auth/management/commands/bulkimportusers.py:80
msgctxt "Error when the command is executed in the Terminal (command prompt)"
msgid "Value in column '{}' has too many characters"
msgstr "Il valore nella colonna '{}' ha troppi caratteri"

#: core/auth/management/commands/bulkimportusers.py:82
msgid "Value in column '{}' not valid"
msgstr "Valore nella colonna '{}' non valido"

#: core/auth/management/commands/bulkimportusers.py:83
msgid "Username is duplicated"
msgstr "Il nome utente è duplicato"

#: core/auth/management/commands/bulkimportusers.py:89
msgctxt "Error message indicating that the CSV file selected for import is missing a required column"
msgid "The column '{}' is required"
msgstr "La colonna \"{}\" è obbligatoria"

#: core/auth/management/commands/bulkimportusers.py:93
msgctxt "Error message indicating that one column header in the CSV file selected for import is missing or incorrect"
msgid "Incorrect header label found in the first row"
msgstr "Etichetta di intestazione errata trovata nella prima riga"

#: core/auth/management/commands/bulkimportusers.py:97
msgctxt "Error when the command is executed in the Terminal (command prompt)"
msgid "No default facility exists. Make sure to set up a facility on the  device before importing users and classes"
msgstr "Non esiste nessuna struttura predefinita. Assicurati di impostare una struttura sul dispositivo prima di importare utenti e classi"

#: core/auth/management/commands/bulkimportusers.py:102
msgid "The password field is required. To leave the password unchanged in existing users, insert an asterisk (*)"
msgstr "Il campo password è obbligatorio. Per lasciare invariata la password negli utenti esistenti, inserire un asterisco (*)"

#: core/auth/management/commands/bulkimportusers.py:105
msgid "Cannot update user with ID: '{}' because no user with that database ID exists in this facility"
msgstr "Impossibile aggiornare l'utente con ID: '{}' perché non esiste nessun utente con questo ID nel database"

#: core/auth/management/commands/bulkimportusers.py:107
msgid "Database ID is not valid"
msgstr "L'ID del database non è valido"

#: core/content/api.py:170
msgid "Resource"
msgstr "Risorsa"

#: core/content/api.py:1327
msgid "The requested channel does not exist on the content server"
msgstr "Il canale richiesto non esiste sul server dei contenuti"

#: core/content/models.py:252
msgid "Unknown format"
msgstr "Formato sconosciuto"

#: core/device/serializers.py:36
msgid "Language is not supported by Kolibri"
msgstr "La lingua non è supportata da Kolibri"

#: core/logger/csv_export.py:205
msgctxt "Default name for the exported CSV file with content session logs. Please keep the underscores between words in the translation"
msgid "content_session_logs"
msgstr "log_contenuto_sessione"

#: core/logger/csv_export.py:215
msgctxt "Default name for the exported CSV file with content summary logs. Please keep the underscores between words in the translation"
msgid "content_summary_logs"
msgstr "log_riepilogo_contenuto"

#: core/tasks/api.py:82
msgid "There was a network error."
msgstr "Si è verificato un errore di rete."

#: core/tasks/api.py:84
msgid "There was a disk access error."
msgstr "Si è verificato un errore di accesso al disco."

#: core/tasks/api.py:86
msgid "There was an unknown error."
msgstr "Si è verificato un errore sconosciuto."

#: core/templates/kolibri/base.html:13
#: core/templates/kolibri/unsupported_browser.html:13
msgid "Kolibri"
msgstr "Kolibri"

#: core/templates/kolibri/unsupported_browser.html:42
msgid "Unsupported browser"
msgstr "Browser non supportato"

#: core/templates/kolibri/unsupported_browser.html:43
msgid "Sorry, your browser version is not supported."
msgstr "Spiacenti, la versione del tuo browser non è supportata."

#: core/templates/kolibri/unsupported_browser.html:44
msgid "To use Kolibri, we recommend using Firefox or Chrome."
msgstr "Per utilizzare Kolibri, si consiglia di utilizzare Firefox o Chrome."

#: core/templates/kolibri/unsupported_browser.html:45
msgid "You can also try updating your current browser."
msgstr "Puoi anche provare ad aggiornare il tuo browser attuale."

#: core/views.py:168
msgid "No appropriate redirect pages found. It is likely that Kolibri is badly configured"
msgstr "Non sono state trovate pagine di reindirizzamento appropriate. È probabile che Kolibri non sia configurato correttamente"

#: plugins/facility/views.py:52
msgctxt "Default name for the exported CSV file of facility user data. Please keep the underscore between words in the translation"
msgid "users_{}"
msgstr "utenti_{}"

