msgid ""
msgstr ""
"Project-Id-Version: kolibri\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-07-29 15:05-0700\n"
"PO-Revision-Date: 2021-08-13 22:36\n"
"Last-Translator: \n"
"Language-Team: Portuguese, Brazilian\n"
"Language: pt_BR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: kolibri\n"
"X-Crowdin-Project-ID: 201933\n"
"X-Crowdin-Language: pt-BR\n"
"X-Crowdin-File: /release-v0.15.x/django.po\n"
"X-Crowdin-File-ID: 4105\n"

#: core/auth/constants/commands_errors.py:17
msgid "Unexpected exception [{}]: {}"
msgstr "Exceção inesperada [{}]: {}"

#: core/auth/constants/commands_errors.py:20
msgctxt "Error report message when the allowed number of digits has been exceeded."
msgid "Content of cell '{}' is too long"
msgstr "O conteúdo da célula '{}' tem muitos caracteres"

#: core/auth/constants/commands_errors.py:24
msgctxt "Error report message when the cell contains an improper data format."
msgid "Content of cell '{}' is not valid"
msgstr "O conteúdo da célula '{}' não é válido"

#: core/auth/constants/commands_errors.py:26
msgid "Duplicated username"
msgstr "Esse nome de usuário já existe"

#: core/auth/constants/commands_errors.py:28
#: core/auth/management/commands/bulkimportusers.py:85
msgid "Username only can contain characters, numbers and underscores"
msgstr "O nome de usuário deve conter somente letras, números e sublinhados"

#: core/auth/constants/commands_errors.py:30
msgid "The column '{}' is required"
msgstr "Os campos da coluna '{}' são obrigatórios"

#: core/auth/constants/commands_errors.py:31
msgid "Mix of valid and/or invalid header labels found in first row"
msgstr "Há alguns cabeçalhos inválidos na primeira linha"

#: core/auth/constants/commands_errors.py:33
msgid "No default facility exists. Make sure to set up a facility on the device before running this command"
msgstr "Não há nenhum centro educativo configurado. Faça a configuração antes de executar este comando"

#: core/auth/constants/commands_errors.py:35
#: core/auth/management/commands/bulkimportusers.py:99
msgid "Error trying to read csv file: {}"
msgstr "Erro de leitura do arquivo csv: {}"

#: core/auth/constants/commands_errors.py:36
#: core/auth/management/commands/bulkimportusers.py:100
msgid "Error trying to write csv file: {}"
msgstr "Erro ao tentar escrever o arquivo csv: {}"

#: core/auth/management/commands/bulkexportusers.py:42
#: core/auth/management/commands/bulkexportusers.py:124
msgid "Database ID ({})"
msgstr "Identificador ID do banco de dados ({})"

#: core/auth/management/commands/bulkexportusers.py:43
#: core/auth/management/commands/bulkexportusers.py:125
msgid "Username ({})"
msgstr "Nome de usuário ({})"

#: core/auth/management/commands/bulkexportusers.py:44
#: core/auth/management/commands/bulkexportusers.py:126
msgid "Password ({})"
msgstr "Senha ({})"

#: core/auth/management/commands/bulkexportusers.py:45
#: core/auth/management/commands/bulkexportusers.py:127
msgid "Full name ({})"
msgstr "Nome completo ({})"

#: core/auth/management/commands/bulkexportusers.py:50
msgctxt "CSV column header for the type of user: ADMIN, LEARNER, COACH..."
msgid "User type ({})"
msgstr "Tipo de usuário ({})"

#: core/auth/management/commands/bulkexportusers.py:53
#: core/auth/management/commands/bulkexportusers.py:135
msgid "Identifier ({})"
msgstr "Identificador ({})"

#: core/auth/management/commands/bulkexportusers.py:54
#: core/auth/management/commands/bulkexportusers.py:136
msgid "Birth year ({})"
msgstr "Ano de nascimento ({})"

#: core/auth/management/commands/bulkexportusers.py:55
#: core/auth/management/commands/bulkexportusers.py:137
msgid "Gender ({})"
msgstr "Gênero ({})"

#: core/auth/management/commands/bulkexportusers.py:60
msgctxt "CSV column header for the list of classrooms names where the learner is going to be enrolled"
msgid "Learner enrollment ({})"
msgstr "Alunos inscritos ({})"

#: core/auth/management/commands/bulkexportusers.py:67
msgctxt "CSV column header for the list of classrooms names where the tutor is going to be a coach"
msgid "Coach assignment ({})"
msgstr "Professores inscritos ({})"

#: core/auth/management/commands/bulkexportusers.py:132
msgctxt "CSV header for the type of user: ADMIN, LEARNER, COACH..."
msgid "User type ({})"
msgstr "Tipo de usuário ({})"

#: core/auth/management/commands/bulkexportusers.py:142
msgctxt "CSV file header for the list of classrooms names where the learner is going to be enrolled"
msgid "Learner enrollment ({})"
msgstr "Alunos inscritos ({})"

#: core/auth/management/commands/bulkexportusers.py:149
msgctxt "CSV file header for the list of classrooms names where the tutor is going to be a coach"
msgid "Coach assignment ({})"
msgstr "Professores inscritos ({})"

#: core/auth/management/commands/bulkimportusers.py:76
msgctxt "Error message that might appear when there's a programming error importing a CSV file"
msgid "Unexpected error [{}]: {}"
msgstr "Erro inesperado [{}]: {}"

#: core/auth/management/commands/bulkimportusers.py:80
msgctxt "Error when the command is executed in the Terminal (command prompt)"
msgid "Value in column '{}' has too many characters"
msgstr "O valor da coluna '{}' tem muitos caracteres"

#: core/auth/management/commands/bulkimportusers.py:82
msgid "Invalid value in column '{}'"
msgstr "Há algum valor inválido na coluna '{}'  "

#: core/auth/management/commands/bulkimportusers.py:83
msgid "Username is duplicated"
msgstr "Este nome de usuário já existe"

#: core/auth/management/commands/bulkimportusers.py:89
msgctxt "Error message indicating that the CSV file selected for import is missing a required column"
msgid "The column '{}' is required"
msgstr "Os campos da coluna '{}' são obrigatórios"

#: core/auth/management/commands/bulkimportusers.py:93
msgctxt "Error message indicating that one column header in the CSV file selected for import is missing or incorrect"
msgid "Invalid header label found in the first row"
msgstr "Há algum cabeçalho inválido na primeira linha  "

#: core/auth/management/commands/bulkimportusers.py:97
msgctxt "Error when the command is executed in the Terminal (command prompt)"
msgid "No default facility exists. Make sure to set up a facility on the  device before importing users and classes"
msgstr "Não há um centro educativo padrão configurado. Por favor configure um centro educativo neste dispositivo antes de importar usuários e classes"

#: core/auth/management/commands/bulkimportusers.py:102
msgid "The password field is required. To leave the password unchanged in existing users, insert an asterisk (*)"
msgstr "O campo \"senha\" é obrigatório. Para manter a senha dos usuários existentes, por favor insira um asterisco (*)"

#: core/auth/management/commands/bulkimportusers.py:105
msgid "Cannot update user with ID: '{}' because no user with that database ID exists in this facility"
msgstr "Não foi possível atualizar o usuário ID: '{}' porque nenhum usuário com esse ID existe neste centro educativo"

#: core/auth/management/commands/bulkimportusers.py:107
msgid "Database ID is not valid"
msgstr "O ID deste banco de dados não é valido"

#: core/content/api.py:152
msgid "Resource"
msgstr "Conteúdo"

#: core/content/api.py:1269
msgid "The requested channel does not exist on the content server"
msgstr "O canal solicitado não existe no servidor de conteúdo"

#: core/content/models.py:220
msgid "Unknown format"
msgstr "Formato desconhecido"

#: core/device/serializers.py:41
msgid "Language is not supported by Kolibri"
msgstr "Kolibri ainda não está disponível neste idioma"

#: core/logger/csv_export.py:204
msgctxt "Default name for the exported CSV file with content session logs. Please keep the underscores between words in the translation"
msgid "content_session_logs"
msgstr "sessões_únicas_por_recurso"

#: core/logger/csv_export.py:214
msgctxt "Default name for the exported CSV file with content summary logs. Please keep the underscores between words in the translation"
msgid "content_summary_logs"
msgstr "resumo_sessões_por_recurso"

#: core/tasks/api.py:82
msgid "There was a network error."
msgstr "Ocorreu um erro de rede."

#: core/tasks/api.py:84
msgid "There was a disk access error."
msgstr "Houve um erro ao acessar o disco."

#: core/tasks/api.py:86
msgid "There was an unknown error."
msgstr "Ocorreu um erro desconhecido."

#: core/templates/kolibri/base.html:13
#: core/templates/kolibri/unsupported_browser.html:13
msgid "Kolibri"
msgstr "Kolibri"

#: core/templates/kolibri/unsupported_browser.html:42
msgid "Unsupported browser"
msgstr "Navegador incompatível"

#: core/templates/kolibri/unsupported_browser.html:43
msgid "Sorry, your browser version is not supported."
msgstr "Desculpe, esta versão do seu navegador não é compatível."

#: core/templates/kolibri/unsupported_browser.html:44
msgid "To use Kolibri, we recommend using Firefox or Chrome."
msgstr "Para usar Kolibri, recomendamos utilizar Firefox ou Chrome."

#: core/templates/kolibri/unsupported_browser.html:45
msgid "You can also try updating your current browser."
msgstr "Você também pode tentar atualizar seu navegador."

#: core/views.py:161
msgid "No appropriate redirect pages found. It is likely that Kolibri is badly configured"
msgstr "Nenhuma página de redirecionamento foi encontrada. É provável que Kolibri tenha sido mal configurado"

#: plugins/facility/views.py:52
msgctxt "Default name for the exported CSV file of facility user data. Please keep the underscore between words in the translation"
msgid "users_{}"
msgstr "usuários_{}"

