msgid ""
msgstr ""
"Project-Id-Version: kolibri\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-07-29 15:05-0700\n"
"PO-Revision-Date: 2021-08-13 22:36\n"
"Last-Translator: \n"
"Language-Team: German\n"
"Language: de_DE\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: kolibri\n"
"X-Crowdin-Project-ID: 201933\n"
"X-Crowdin-Language: de\n"
"X-Crowdin-File: /release-v0.15.x/django.po\n"
"X-Crowdin-File-ID: 4105\n"

#: core/auth/constants/commands_errors.py:17
msgid "Unexpected exception [{}]: {}"
msgstr "Unerwarteter Ausnahmefehler [{}]: {}"

#: core/auth/constants/commands_errors.py:20
msgctxt "Error report message when the allowed number of digits has been exceeded."
msgid "Content of cell '{}' is too long"
msgstr "Inhalt der Zelle '{}' ist zu lang"

#: core/auth/constants/commands_errors.py:24
msgctxt "Error report message when the cell contains an improper data format."
msgid "Content of cell '{}' is not valid"
msgstr "Inhalt der Zelle '{}' ist ungültig"

#: core/auth/constants/commands_errors.py:26
msgid "Duplicated username"
msgstr "Benutzername bereits vorhanden"

#: core/auth/constants/commands_errors.py:28
#: core/auth/management/commands/bulkimportusers.py:85
msgid "Username only can contain characters, numbers and underscores"
msgstr "Benutzername darf nur Buchstaben, Ziffern und Unterstriche enthalten"

#: core/auth/constants/commands_errors.py:30
msgid "The column '{}' is required"
msgstr "Die Spalte '{}' ist erforderlich"

#: core/auth/constants/commands_errors.py:31
msgid "Mix of valid and/or invalid header labels found in first row"
msgstr "Einige ungültige Spaltenüberschriften in der ersten Zeile gefunden"

#: core/auth/constants/commands_errors.py:33
msgid "No default facility exists. Make sure to set up a facility on the device before running this command"
msgstr "Es ist keine standardmäßige Einrichtung vorhanden. Vor dem Ausführen dieses Befehls sollte eine Einrichtung auf dem Gerät erstellt werden."

#: core/auth/constants/commands_errors.py:35
#: core/auth/management/commands/bulkimportusers.py:99
msgid "Error trying to read csv file: {}"
msgstr "Fehler beim Lesen der CSV-Datei: {}"

#: core/auth/constants/commands_errors.py:36
#: core/auth/management/commands/bulkimportusers.py:100
msgid "Error trying to write csv file: {}"
msgstr "Fehler beim Schreiben der CSV-Datei: {}"

#: core/auth/management/commands/bulkexportusers.py:42
#: core/auth/management/commands/bulkexportusers.py:124
msgid "Database ID ({})"
msgstr "Datenbank-ID ({})"

#: core/auth/management/commands/bulkexportusers.py:43
#: core/auth/management/commands/bulkexportusers.py:125
msgid "Username ({})"
msgstr "Benutzername ({})"

#: core/auth/management/commands/bulkexportusers.py:44
#: core/auth/management/commands/bulkexportusers.py:126
msgid "Password ({})"
msgstr "Passwort ({})"

#: core/auth/management/commands/bulkexportusers.py:45
#: core/auth/management/commands/bulkexportusers.py:127
msgid "Full name ({})"
msgstr "Vollständiger Name ({})"

#: core/auth/management/commands/bulkexportusers.py:50
msgctxt "CSV column header for the type of user: ADMIN, LEARNER, COACH..."
msgid "User type ({})"
msgstr "Benutzertyp ({})"

#: core/auth/management/commands/bulkexportusers.py:53
#: core/auth/management/commands/bulkexportusers.py:135
msgid "Identifier ({})"
msgstr "Kennung ({})"

#: core/auth/management/commands/bulkexportusers.py:54
#: core/auth/management/commands/bulkexportusers.py:136
msgid "Birth year ({})"
msgstr "Geburtsjahr ({})"

#: core/auth/management/commands/bulkexportusers.py:55
#: core/auth/management/commands/bulkexportusers.py:137
msgid "Gender ({})"
msgstr "Geschlecht ({})"

#: core/auth/management/commands/bulkexportusers.py:60
msgctxt "CSV column header for the list of classrooms names where the learner is going to be enrolled"
msgid "Learner enrollment ({})"
msgstr "Einschreibung des Lernenden ({})"

#: core/auth/management/commands/bulkexportusers.py:67
msgctxt "CSV column header for the list of classrooms names where the tutor is going to be a coach"
msgid "Coach assignment ({})"
msgstr "Trainerzuweisung ({})"

#: core/auth/management/commands/bulkexportusers.py:132
msgctxt "CSV header for the type of user: ADMIN, LEARNER, COACH..."
msgid "User type ({})"
msgstr "Benutzertyp ({})"

#: core/auth/management/commands/bulkexportusers.py:142
msgctxt "CSV file header for the list of classrooms names where the learner is going to be enrolled"
msgid "Learner enrollment ({})"
msgstr "Einschreibung des Lernenden ({})"

#: core/auth/management/commands/bulkexportusers.py:149
msgctxt "CSV file header for the list of classrooms names where the tutor is going to be a coach"
msgid "Coach assignment ({})"
msgstr "Trainerzuweisung ({})"

#: core/auth/management/commands/bulkimportusers.py:76
msgctxt "Error message that might appear when there's a programming error importing a CSV file"
msgid "Unexpected error [{}]: {}"
msgstr "Unerwarteter Fehler [{}]: {}"

#: core/auth/management/commands/bulkimportusers.py:80
msgctxt "Error when the command is executed in the Terminal (command prompt)"
msgid "Value in column '{}' has too many characters"
msgstr "Wert in Spalte '{}' hat zu viele Zeichen"

#: core/auth/management/commands/bulkimportusers.py:82
msgid "Invalid value in column '{}'"
msgstr "Ungültiger Wert in Spalte '{}'"

#: core/auth/management/commands/bulkimportusers.py:83
msgid "Username is duplicated"
msgstr "Benutzername ist bereits vorhanden"

#: core/auth/management/commands/bulkimportusers.py:89
msgctxt "Error message indicating that the CSV file selected for import is missing a required column"
msgid "The column '{}' is required"
msgstr "Die Spalte '{}' ist erforderlich"

#: core/auth/management/commands/bulkimportusers.py:93
msgctxt "Error message indicating that one column header in the CSV file selected for import is missing or incorrect"
msgid "Invalid header label found in the first row"
msgstr "Ungültige Spaltenüberschrift in der ersten Zeile gefunden"

#: core/auth/management/commands/bulkimportusers.py:97
msgctxt "Error when the command is executed in the Terminal (command prompt)"
msgid "No default facility exists. Make sure to set up a facility on the  device before importing users and classes"
msgstr "Es ist keine standardmäßige Einrichtung vorhanden. Vor dem Importieren der Benutzer und Klassen sollte eine Einrichtung auf dem Gerät erstellt werden."

#: core/auth/management/commands/bulkimportusers.py:102
msgid "The password field is required. To leave the password unchanged in existing users, insert an asterisk (*)"
msgstr "Die Eingabe des Passworts ist erforderlich. Um das Passwort vorhandener Benutzer beizubehalten, geben Sie ein Sternchen (*) ein."

#: core/auth/management/commands/bulkimportusers.py:105
msgid "Cannot update user with ID: '{}' because no user with that database ID exists in this facility"
msgstr "Benutzer mit der ID '{}' kann nicht aktualisiert werden, da kein Benutzer mit dieser Datenbank-ID in dieser Einrichtung vorhanden ist."

#: core/auth/management/commands/bulkimportusers.py:107
msgid "Database ID is not valid"
msgstr "Datenbank-ID ist ungültig"

#: core/content/api.py:152
msgid "Resource"
msgstr "Material"

#: core/content/api.py:1269
msgid "The requested channel does not exist on the content server"
msgstr "Der gewünschte Kanal existiert nicht auf dem Content server"

#: core/content/models.py:220
msgid "Unknown format"
msgstr "Unbekanntes format"

#: core/device/serializers.py:41
msgid "Language is not supported by Kolibri"
msgstr "Diese Sprache wird von Kolibri nicht unterstützt"

#: core/logger/csv_export.py:204
msgctxt "Default name for the exported CSV file with content session logs. Please keep the underscores between words in the translation"
msgid "content_session_logs"
msgstr "Inhalt_Sitzungsprotokolle"

#: core/logger/csv_export.py:214
msgctxt "Default name for the exported CSV file with content summary logs. Please keep the underscores between words in the translation"
msgid "content_summary_logs"
msgstr "Inhalt_Übersichtsprotokolle"

#: core/tasks/api.py:82
msgid "There was a network error."
msgstr "Ein Netzwerkfehler ist aufgetreten."

#: core/tasks/api.py:84
msgid "There was a disk access error."
msgstr "Fehler beim Festplattenzugriff."

#: core/tasks/api.py:86
msgid "There was an unknown error."
msgstr "Ein unbekannter Fehler ist aufgetreten."

#: core/templates/kolibri/base.html:13
#: core/templates/kolibri/unsupported_browser.html:13
msgid "Kolibri"
msgstr "Kolibri"

#: core/templates/kolibri/unsupported_browser.html:42
msgid "Unsupported browser"
msgstr "Nicht unterstützter Browser"

#: core/templates/kolibri/unsupported_browser.html:43
msgid "Sorry, your browser version is not supported."
msgstr "Ihre Browserversion wird leider nicht unterstützt."

#: core/templates/kolibri/unsupported_browser.html:44
msgid "To use Kolibri, we recommend using Firefox or Chrome."
msgstr "Wir empfehlen Firefox oder Chrome für die Nutzung von Kolibri."

#: core/templates/kolibri/unsupported_browser.html:45
msgid "You can also try updating your current browser."
msgstr "Möglicherweise können Sie den Fehler beheben, indem Sie Ihre Browserversion aktualisieren."

#: core/views.py:161
msgid "No appropriate redirect pages found. It is likely that Kolibri is badly configured"
msgstr "Es wurden keine entsprechenden Weiterleitungsseiten gefunden. Möglicherweise wurde Kolibri nicht ordnungsgemäß konfiguriert."

#: plugins/facility/views.py:52
msgctxt "Default name for the exported CSV file of facility user data. Please keep the underscore between words in the translation"
msgid "users_{}"
msgstr "Benutzer_{}"

