msgid ""
msgstr ""
"Project-Id-Version: kolibri\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-07-29 15:05-0700\n"
"PO-Revision-Date: 2021-08-13 22:36\n"
"Last-Translator: \n"
"Language-Team: Bulgarian\n"
"Language: bg_BG\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: kolibri\n"
"X-Crowdin-Project-ID: 201933\n"
"X-Crowdin-Language: bg\n"
"X-Crowdin-File: /release-v0.15.x/django.po\n"
"X-Crowdin-File-ID: 4105\n"

#: core/auth/constants/commands_errors.py:17
msgid "Unexpected exception [{}]: {}"
msgstr "Неочаквано грешка [{}]: {}"

#: core/auth/constants/commands_errors.py:20
msgctxt "Error report message when the allowed number of digits has been exceeded."
msgid "Content of cell '{}' is too long"
msgstr "Съдържанието на клетка '{}' е твърде дълго"

#: core/auth/constants/commands_errors.py:24
msgctxt "Error report message when the cell contains an improper data format."
msgid "Content of cell '{}' is not valid"
msgstr "Съдържанието на клетка '{}' е невалидно"

#: core/auth/constants/commands_errors.py:26
msgid "Duplicated username"
msgstr "Дублиране на име"

#: core/auth/constants/commands_errors.py:28
#: core/auth/management/commands/bulkimportusers.py:85
msgid "Username only can contain characters, numbers and underscores"
msgstr "Потребителското име може да съдържа само букви, цифри и долни черти"

#: core/auth/constants/commands_errors.py:30
msgid "The column '{}' is required"
msgstr "Колоната '{}' е задължителна"

#: core/auth/constants/commands_errors.py:31
msgid "Mix of valid and/or invalid header labels found in first row"
msgstr "Смесица от валидни и/или невалидни етикети на заглавията, открити в първия ред"

#: core/auth/constants/commands_errors.py:33
msgid "No default facility exists. Make sure to set up a facility on the device before running this command"
msgstr "Не съществува институция по подразбиране. Не забравяй да настроиш институция на устройството, преди да изпълниш тази команда"

#: core/auth/constants/commands_errors.py:35
#: core/auth/management/commands/bulkimportusers.py:99
msgid "Error trying to read csv file: {}"
msgstr "Грешка при опит за четене на csv файл: {}"

#: core/auth/constants/commands_errors.py:36
#: core/auth/management/commands/bulkimportusers.py:100
msgid "Error trying to write csv file: {}"
msgstr "Грешка при запис в csv файл: {}"

#: core/auth/management/commands/bulkexportusers.py:42
#: core/auth/management/commands/bulkexportusers.py:124
msgid "Database ID ({})"
msgstr "База данни ID ({})"

#: core/auth/management/commands/bulkexportusers.py:43
#: core/auth/management/commands/bulkexportusers.py:125
msgid "Username ({})"
msgstr "Потребителско име ({})"

#: core/auth/management/commands/bulkexportusers.py:44
#: core/auth/management/commands/bulkexportusers.py:126
msgid "Password ({})"
msgstr "Парола ({})"

#: core/auth/management/commands/bulkexportusers.py:45
#: core/auth/management/commands/bulkexportusers.py:127
msgid "Full name ({})"
msgstr "Пълно име ({})"

#: core/auth/management/commands/bulkexportusers.py:50
msgctxt "CSV column header for the type of user: ADMIN, LEARNER, COACH..."
msgid "User type ({})"
msgstr "Вид потребител ({})"

#: core/auth/management/commands/bulkexportusers.py:53
#: core/auth/management/commands/bulkexportusers.py:135
msgid "Identifier ({})"
msgstr "Идентификатор ({})"

#: core/auth/management/commands/bulkexportusers.py:54
#: core/auth/management/commands/bulkexportusers.py:136
msgid "Birth year ({})"
msgstr "Година на раждане ({})"

#: core/auth/management/commands/bulkexportusers.py:55
#: core/auth/management/commands/bulkexportusers.py:137
msgid "Gender ({})"
msgstr "Пол ({})"

#: core/auth/management/commands/bulkexportusers.py:60
msgctxt "CSV column header for the list of classrooms names where the learner is going to be enrolled"
msgid "Learner enrollment ({})"
msgstr "Записване на ученик ({})"

#: core/auth/management/commands/bulkexportusers.py:67
msgctxt "CSV column header for the list of classrooms names where the tutor is going to be a coach"
msgid "Coach assignment ({})"
msgstr "Учителско назначение ({})"

#: core/auth/management/commands/bulkexportusers.py:132
msgctxt "CSV header for the type of user: ADMIN, LEARNER, COACH..."
msgid "User type ({})"
msgstr "Вид потребител ({})"

#: core/auth/management/commands/bulkexportusers.py:142
msgctxt "CSV file header for the list of classrooms names where the learner is going to be enrolled"
msgid "Learner enrollment ({})"
msgstr "Записване на ученик ({})"

#: core/auth/management/commands/bulkexportusers.py:149
msgctxt "CSV file header for the list of classrooms names where the tutor is going to be a coach"
msgid "Coach assignment ({})"
msgstr "Учителско назначение ({})"

#: core/auth/management/commands/bulkimportusers.py:76
msgctxt "Error message that might appear when there's a programming error importing a CSV file"
msgid "Unexpected error [{}]: {}"
msgstr "Неочаквана грешка [{}]: {}"

#: core/auth/management/commands/bulkimportusers.py:80
msgctxt "Error when the command is executed in the Terminal (command prompt)"
msgid "Value in column '{}' has too many characters"
msgstr "Стойността в колона '{}' има прекалено много символи"

#: core/auth/management/commands/bulkimportusers.py:82
msgid "Invalid value in column '{}'"
msgstr "Невалидна стойност в колона '{}'"

#: core/auth/management/commands/bulkimportusers.py:83
msgid "Username is duplicated"
msgstr "Потребителското име се повтаря"

#: core/auth/management/commands/bulkimportusers.py:89
msgctxt "Error message indicating that the CSV file selected for import is missing a required column"
msgid "The column '{}' is required"
msgstr "Колоната '{}' е задължителна"

#: core/auth/management/commands/bulkimportusers.py:93
msgctxt "Error message indicating that one column header in the CSV file selected for import is missing or incorrect"
msgid "Invalid header label found in the first row"
msgstr "Невалидни етикети на заглавията, открити в първия ред"

#: core/auth/management/commands/bulkimportusers.py:97
msgctxt "Error when the command is executed in the Terminal (command prompt)"
msgid "No default facility exists. Make sure to set up a facility on the  device before importing users and classes"
msgstr "Не съществува институция по подразбиране. Не забравяй да настроиш институция на устройството, преди да импортираш потребители и класове"

#: core/auth/management/commands/bulkimportusers.py:102
msgid "The password field is required. To leave the password unchanged in existing users, insert an asterisk (*)"
msgstr "Полето за парола е задължително. За да оставиш парола непроменена при съществуващ потребител, постави звездичка (*)"

#: core/auth/management/commands/bulkimportusers.py:105
msgid "Cannot update user with ID: '{}' because no user with that database ID exists in this facility"
msgstr "Не може да обнови потребител с идентификационен номер: '{}', защото в базата данни на институцията не съществува потребител с такъв идентификационен номер"

#: core/auth/management/commands/bulkimportusers.py:107
msgid "Database ID is not valid"
msgstr "Идентификационният номер на базата данни не е валиден"

#: core/content/api.py:152
msgid "Resource"
msgstr "Ресурс"

#: core/content/api.py:1269
msgid "The requested channel does not exist on the content server"
msgstr "Този канал не съществува на сървъра с материали"

#: core/content/models.py:220
msgid "Unknown format"
msgstr "Неизвестен формат"

#: core/device/serializers.py:41
msgid "Language is not supported by Kolibri"
msgstr "Този език не се поддържа от Колибри"

#: core/logger/csv_export.py:204
msgctxt "Default name for the exported CSV file with content session logs. Please keep the underscores between words in the translation"
msgid "content_session_logs"
msgstr "content_session_logs"

#: core/logger/csv_export.py:214
msgctxt "Default name for the exported CSV file with content summary logs. Please keep the underscores between words in the translation"
msgid "content_summary_logs"
msgstr "content_summary_logs"

#: core/tasks/api.py:82
msgid "There was a network error."
msgstr "Възникна грешка в мрежата."

#: core/tasks/api.py:84
msgid "There was a disk access error."
msgstr "Възникна грешка с достъпа до устройството."

#: core/tasks/api.py:86
msgid "There was an unknown error."
msgstr "Възникна неизвестна грешка."

#: core/templates/kolibri/base.html:13
#: core/templates/kolibri/unsupported_browser.html:13
msgid "Kolibri"
msgstr "Колибри"

#: core/templates/kolibri/unsupported_browser.html:42
msgid "Unsupported browser"
msgstr "Неподдържан браузър"

#: core/templates/kolibri/unsupported_browser.html:43
msgid "Sorry, your browser version is not supported."
msgstr "Съжаляваме, тази версия на браузъра не се поддържа."

#: core/templates/kolibri/unsupported_browser.html:44
msgid "To use Kolibri, we recommend using Firefox or Chrome."
msgstr "За използване на Колибри препоръчваме Firefox или Chrome."

#: core/templates/kolibri/unsupported_browser.html:45
msgid "You can also try updating your current browser."
msgstr "Можш също да опиташ да актуализираш текущия си браузър."

#: core/views.py:161
msgid "No appropriate redirect pages found. It is likely that Kolibri is badly configured"
msgstr "Не са намерени подходящи страници за пренасочване. Вероятно се дължи на неправилна конфигурация на Колибри"

#: plugins/facility/views.py:52
msgctxt "Default name for the exported CSV file of facility user data. Please keep the underscore between words in the translation"
msgid "users_{}"
msgstr "users_{}"

